### ISSUE TITLE
M=的导入

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng-public-data#1]
https://docs.google.com/spreadsheets/d/1atfKrRnhYoeYVz56vy2Im9SJtfmFBS0oYjt0l8l8G0w/edit#gid=136291253

**Comment by Guanchishan** [comment]
导入工作目前做得怎么样了？现在我需要给一位志愿者分派任务了

**Comment by Guanchishan** [comment]
看起来是为了元宵大挑战做的导入吗？

**Comment by Guanchishan** [comment]
我注意到M和P在迁移 那么S这个参数有在迁移吗

**Comment by Guanchishan** [comment]
如果我現在探索用一些機械手段（雖然怎麼做有待學習）將[這張表格](https://docs.google.com/spreadsheets/d/1atfKrRnhYoeYVz56vy2Im9SJtfmFBS0oYjt0l8l8G0w/edit#gid=136291253)的數據導入zingzeu_words，這是否會對真鳥囝現有的任何業務、計劃造成影響？若無，打算試着導進去下，一個是優化搜索結果，一個是把這個案子也可以階段性結束一下。

**Comment by ztl8702** [comment]
> 這是否會對真鳥囝現有的任何業務、計劃造成影響？

只要你以 "创建分支-> 发起 Pull Request" 的方式编辑 ztl8702/zingzeu-data，而非直接 commit 到 master，就不会有什么负面影响。

欢迎发起 Draft Pull Request，供我审核。在 Draft Pull Request 基础上迭代。

> 雖然怎麼做有待學習

可以复制/修改 https://colab.research.google.com/drive/1nEOIT6Bx2CuX4_4cO0xNIiaRr4kwZ9AU 里的代码。

----

抄送 @chenyulin1204 ，请跟踪此任务。

**Comment by Guanchishan** [comment]
分支已建立，工作中。ztl8702/zingzeu-data at insert-M-S-P-into-zingzeu-words-20230420 (github.com) 从 Windows 版邮件发送 发件人: Radium Zheng发送时间: 2023年4月21日 0:29收件人: MindongLab/yngdieng-public-data抄送: Davidzdh; Comment主题: Re: [MindongLab/yngdieng-public-data] M=的导入 (Issue #1) 這是否會對真鳥囝現有的任何業務、計劃造成影響？只要你以 "创建分支-> 发起 Pull Request" 的方式编辑 ztl8702/zingzeu-data，而非直接 commit 到 master，就不会有什么负面影响。欢迎发起 Draft Pull Request，供我审核。在 Draft Pull Request 基础上迭代。雖然怎麼做有待學習可以复制/修改 https://colab.research.google.com/drive/1nEOIT6Bx2CuX4_4cO0xNIiaRr4kwZ9AU 里的代码。抄送 @chenyulin1204 ，请跟踪此任务。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by ztl8702** [comment]
Sounds good. I will have a closer look once you create the pull request.
